### Check server health
GET http://localhost:8080/health

### Get user transactions
GET http://localhost:8080/api/v1/transactions?limit=5&offset=0
Content-Type: application/json
Authorization: {{token}}

### Get user transactions with date
GET http://localhost:8080/api/v1/transactions?from_date=2026-01-10
Content-Type: application/json
Authorization: {{token}}

### Get user transactions with tags
GET http://localhost:8080/api/v1/transactions?from_date=2026-01-01&tags=f69ef826-2a6e-4b29-a66e-236618973e60&
    tags=5f7752f2-ce91-4562-81a0-b044b652ffae
Content-Type: application/json
Authorization: {{token}}

###