### Check server health
GET {{host}}/health

### Get user transactions
GET {{host}}/api/v1/transactions?limit=25&offset=0
Content-Type: application/json
Authorization: {{token}}

### Get user transactions with date
GET {{host}}/api/v1/transactions?from_date=2026-01-10
Content-Type: application/json
Authorization: {{token}}

### Get user transactions with tags
GET {{host}}/api/v1/transactions?from_date=2026-01-01&tags=7ef97619-3f1a-4e1e-8e91-943031b0da56&
    tags=5d230bc5-5066-4de4-a50a-af95fb23eb67
Content-Type: application/json
Authorization: {{token}}

### Get accounts
GET {{host}}/api/v1/accounts
Content-Type: application/json
Authorization: {{token}}

### Get tags
GET {{host}}/api/v1/tags
Content-Type: application/json
Authorization: {{token}}

### Get merchants
GET {{host}}/api/v1/merchants
Content-Type: application/json
Authorization: {{token}}

### Get instruments
GET {{host}}/api/v1/instruments
Content-Type: application/json
Authorization: {{token}}

### Create expence transaction
POST {{host}}/api/v1/transactions/expenses
Authorization: {{token}}
Content-Type: application/json

{
  "transactionId": "3fa85f64-5717-4562-b3fc-2c963f66afa8",
  "accountId": "469107bd-3055-4539-babd-c8037f22a117",
  "tagId": "1fe68d85-731f-46d6-90d2-2a29b1dd5092",
  "amount": 2.70,
  "merchantId": null,
  "merchantName": "Киоск",
  "comment": "Еще одна кола....",
  "date": "2026-01-18"
}

### Create income transaction
POST {{host}}/api/v1/transactions/incomes
Authorization: {{token}}
Content-Type: application/json

{
  "transactionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "accountId": "469107bd-3055-4539-babd-c8037f22a117",
  "tagId": "5d230bc5-5066-4de4-a50a-af95fb23eb67",
  "amount": 50,
  "merchantId": "6a14b79b-9f5b-4b42-b6bf-932878d84b5c",
  "merchantName": "string",
  "comment": "мини-премия",
  "date": "2026-01-18"
}

###