### Check server health
GET http://localhost:8080/health

### Get user transactions
GET http://localhost:8080/api/v1/transactions?limit=25&offset=0
Content-Type: application/json
Authorization: {{token}}

### Get user transactions with date
GET http://localhost:8080/api/v1/transactions?from_date=2026-01-10
Content-Type: application/json
Authorization: {{token}}

### Get user transactions with tags
GET http://localhost:8080/api/v1/transactions?from_date=2026-01-01&tags=7ef97619-3f1a-4e1e-8e91-943031b0da56&
    tags=5d230bc5-5066-4de4-a50a-af95fb23eb67
Content-Type: application/json
Authorization: {{token}}

### Get tags
GET http://localhost:8080/api/v1/tags
Content-Type: application/json
Authorization: {{token}}

### Get merchants
GET http://localhost:8080/api/v1/merchants
Content-Type: application/json
Authorization: {{token}}

### Get instruments
GET http://localhost:8080/api/v1/instruments
Content-Type: application/json
Authorization: {{token}}

### Create expence transaction
POST http://localhost:8080/api/v1/transactions/expenses
Authorization: {{token}}
Content-Type: application/json

{
  "idempotencyKey": "3fa85f64-5717-4562-b3fc-2c963f66afa7",
  "accountId": "469107bd-3055-4539-babd-c8037f22a117",
  "tagId": "7ef97619-3f1a-4e1e-8e91-943031b0da56",
  "amount": 14.12,
  "merchantId": null,
  "merchantName": "Какой-нибудь мерчант-хуенчант",
  "comment": "Купил вчера херни и радуюсь",
  "date": "2026-01-17"
}

### Create income transaction
POST http://localhost:8080/api/v1/transactions/incomes
Authorization: {{token}}
Content-Type: application/json

{
  "transactionId": "3fa85f64-5717-4562-b3fc-2c963f66afa0",
  "accountId": "469107bd-3055-4539-babd-c8037f22a117",
  "tagId": "5d230bc5-5066-4de4-a50a-af95fb23eb67",
  "amount": 250,
  "merchantId": "6a14b79b-9f5b-4b42-b6bf-932878d84b5c",
  "merchantName": "string",
  "comment": "премия!",
  "date": "2026-01-18"
}

###