"""init

Revision ID: 0dbc34e96839
Revises: 1ca405d64f0a
Create Date: 2026-01-18 01:30:30.287530

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dbc34e96839"
down_revision: str | Sequence[str] | None = "1ca405d64f0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transactions", "latitude", existing_type=sa.NUMERIC(), type_=sa.FLOAT(), existing_nullable=True)
    op.alter_column("transactions", "longitude", existing_type=sa.NUMERIC(), type_=sa.FLOAT(), existing_nullable=True)
    op.alter_column("user", "country", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("user", "subscription", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "subscription", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "country", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("transactions", "longitude", existing_type=sa.FLOAT(), type_=sa.NUMERIC(), existing_nullable=True)
    op.alter_column("transactions", "latitude", existing_type=sa.FLOAT(), type_=sa.NUMERIC(), existing_nullable=True)
    # ### end Alembic commands ###
