"""init

Revision ID: 1366eeceff39
Revises: ca4c1e882eb9
Create Date: 2026-01-11 01:34:55.686168

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1366eeceff39"
down_revision: str | Sequence[str] | None = "ca4c1e882eb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("changed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("instrument", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("company", sa.Integer(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("sync_id", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("balance", sa.DECIMAL(), nullable=False),
        sa.Column("start_balance", sa.DECIMAL(), nullable=False),
        sa.Column("credit_limit", sa.DECIMAL(), nullable=False),
        sa.Column("in_balance", sa.Boolean(), nullable=False),
        sa.Column("savings", sa.Boolean(), nullable=False),
        sa.Column("enable_correction", sa.Boolean(), nullable=False),
        sa.Column("enable_sms", sa.Boolean(), nullable=False),
        sa.Column("archive", sa.Boolean(), nullable=False),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("capitalization", sa.Text(), nullable=True),
        sa.Column("percent", sa.DECIMAL(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date_offset", sa.Integer(), nullable=True),
        sa.Column("end_date_offset_interval", sa.Text(), nullable=True),
        sa.Column("payoff_step", sa.Integer(), nullable=True),
        sa.Column("payoff_interval", sa.Text(), nullable=True),
        sa.Column("balance_correction_type", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("changed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("full_title", sa.Text(), nullable=True),
        sa.Column("www", sa.Text(), nullable=True),
        sa.Column("country", sa.Integer(), nullable=True),
        sa.Column("country_code", sa.Text(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "country",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("currency", sa.Integer(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instrument",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("changed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("short_title", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("rate", sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merchant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("changed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("changed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("parent", sa.Uuid(), nullable=True),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("static_id", sa.Text(), nullable=True),
        sa.Column("picture", sa.Text(), nullable=True),
        sa.Column("color", sa.BigInteger(), nullable=True),
        sa.Column("show_income", sa.Boolean(), nullable=False),
        sa.Column("show_outcome", sa.Boolean(), nullable=False),
        sa.Column("budget_income", sa.Boolean(), nullable=False),
        sa.Column("budget_outcome", sa.Boolean(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=True),
        sa.Column("archive", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("changed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.Integer(), nullable=False),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("country", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("login", sa.Text(), nullable=True),
        sa.Column("month_start_day", sa.Integer(), nullable=False),
        sa.Column("is_forecast_enabled", sa.Boolean(), nullable=False),
        sa.Column("plan_balance_mode", sa.Text(), nullable=False),
        sa.Column("plan_settings", sa.Text(), nullable=False),
        sa.Column("paid_till", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subscription", sa.Text(), nullable=False),
        sa.Column("subscription_renewal_date", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("tag")
    op.drop_table("merchant")
    op.drop_table("instrument")
    op.drop_table("country")
    op.drop_table("company")
    op.drop_table("account")
    # ### end Alembic commands ###
