"""init

Revision ID: 5e31f7bdeaba
Revises:
Create Date: 2026-01-10 20:50:45.091420

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e31f7bdeaba"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "last_synced_timestamp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_synced_timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("income", sa.DECIMAL(), nullable=False),
        sa.Column("outcome", sa.DECIMAL(), nullable=False),
        sa.Column("changed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("income_instrument", sa.Integer(), nullable=False),
        sa.Column("outcome_instrument", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("original_payee", sa.Text(), nullable=True),
        sa.Column("deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("viewed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("hold", sa.Boolean(), nullable=True),
        sa.Column("qr_code", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("income_account", sa.Uuid(), nullable=False),
        sa.Column("outcome_account", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("payee", sa.Text(), nullable=True),
        sa.Column("op_income", sa.DECIMAL(), nullable=True),
        sa.Column("op_outcome", sa.DECIMAL(), nullable=True),
        sa.Column("op_income_instrument", sa.Integer(), nullable=True),
        sa.Column("op_outcome_instrument", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.DECIMAL(), nullable=True),
        sa.Column("longitude", sa.DECIMAL(), nullable=True),
        sa.Column("merchant", sa.Text(), nullable=True),
        sa.Column("income_bank_id", sa.Text(), nullable=True),
        sa.Column("outcome_bank_id", sa.Text(), nullable=True),
        sa.Column("reminder_marker", sa.Uuid(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transactions_exist_by_created",
        "transactions",
        ["created"],
        unique=False,
        postgresql_where=sa.text("deleted = false"),
    )
    # ### end Alembic commands ###
    op.execute(
        sa.text(
            "INSERT INTO last_synced_timestamp (id, last_synced_timestamp) "
            "VALUES (1, to_timestamp(0) AT TIME ZONE 'UTC') "
            "ON CONFLICT (id) DO NOTHING"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_transactions_exist_by_created", table_name="transactions", postgresql_where=sa.text("deleted = false")
    )
    op.drop_table("transactions")
    op.drop_table("last_synced_timestamp")
    # ### end Alembic commands ###
