"""init

Revision ID: df1746b31691
Revises: 1366eeceff39
Create Date: 2026-01-12 21:39:49.702903

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df1746b31691"
down_revision: str | Sequence[str] | None = "1366eeceff39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("role", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "role")
    # ### end Alembic commands ###
